### ISSUE TITLE
.gyro not .acceleration

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_L3GD20#6]
The property and documentation is incorrect. This is a gyroscope and not absolute orientation or accelerometer.

**Comment by microbuilder** [comment]
See #7

**Comment by caternuson** [comment]
darn. beat me to it. just got the hardware the other day and had it in the queue. thanks for update!

**Comment by ladyada** [comment]
all good, ktown was also doing some work on the arduino library :)
